# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
 - main

pool:
 vmImage: 'windows-latest'
variables:
  builConfiguration: 'Release'
  outputFolder: 'D:\Deploy\CalcApp'
steps:
  - checkout: self
  - task: UseDotNet@2
    inputs:
      packageType: 'sdk'
      version: '8.x '
 
  - script: dotnet build --configuration $(buildConfiguration) --no-restore --logger "trx"
    displayName: Run Tests
  
      
